import { useState, type FormEvent } from 'react'
import {
  addBlocker, addDecision, addMilestone, addPendingItem, addProgressUpdate, completeMilestone, completeNextAction, completePendingItem, resolveBlocker, setNextAction, updateBlocker, updateNextAction, updatePendingItem,
  type Project, type Workspace,
} from '../domain/workspace'
import type { ContextProject } from '../context-source/types'

interface ProjectDetailProps { workspace: Workspace; project: Project; context: ContextProject | null; onCommit(workspace: Workspace, message: string): void; onClose(): void; onOpenReport(): void }

export function ProjectDetail({ workspace, project, context, onCommit, onClose, onOpenReport }: ProjectDetailProps) {
  const activeAction = workspace.nextActions.find((item) => item.projectId === project.id && !item.completedAt && !item.replacedAt)
  const records = <T extends { projectId: string }>(items: T[]) => items.filter((item) => item.projectId === project.id)
  const latestUpdate = [...records(workspace.progressUpdates)].sort((a, b) => b.occurredOn.localeCompare(a.occurredOn))[0]
  const blockers = records(workspace.blockers).filter((item) => !item.resolvedAt)
  const history = records(workspace.history).sort((a, b) => b.occurredOn.localeCompare(a.occurredOn))
  const commit = (next: Workspace, message: string) => onCommit(next, message)
  const nextCopy = activeAction?.description ?? context?.canonicalNextAction ?? 'Ainda não há uma próxima ação definida.'

  return <section className="detail-view" aria-labelledby="detail-title">
    <header className="detail-top"><div><p className="eyebrow">{context ? 'Contexto consolidado + overlay local' : 'Registro local'}</p><h1 id="detail-title">{project.name}</h1></div><div className="intro-actions"><button className="button-quiet" onClick={onOpenReport}>Gerar relatório</button><button className="button-quiet" onClick={onClose}>Voltar</button></div></header>
    <div className="detail-layout"><div className="detail-primary"><section className="next-decision"><p className="eyebrow">Próxima decisão</p><h2>{nextCopy}</h2>{activeAction && <p>Essa é a ação local ativa. Conclua quando o passo estiver realmente resolvido ou substitua se a leitura mudou.</p>}{!activeAction && context?.canonicalNextAction && <p>Esta é uma sugestão do contexto canônico. Você pode assumir, adaptar ou registrar outra ação local.</p>}<div className="inline-form">{activeAction ? <><button type="button" onClick={() => commit(completeNextAction(workspace, activeAction.id), 'Próxima ação concluída.')}>Concluir ação</button><button type="button" className="button-quiet" onClick={() => editText(activeAction.description, (description) => commit(updateNextAction(workspace, activeAction.id, { description }), 'Próxima ação atualizada.'))}>Editar</button></> : <TextForm label="Definir uma ação local" placeholder="O que precisa acontecer agora?" submitLabel="Salvar ação" onSubmit={(description) => commit(setNextAction(workspace, project.id, { description }), 'Próxima ação definida.')} />}</div></section>
      <section className="detail-block"><p className="section-kicker">Situação</p><h2>Leitura atual</h2><p className="situation-copy">{project.currentSituation || context?.currentSituation || 'Ainda não há uma situação registrada para este projeto.'}</p>{latestUpdate && <p className="situation-copy"><strong>Último avanço · {formatDate(latestUpdate.occurredOn)}</strong><br />{latestUpdate.description}</p>}</section>
      <Fold title={`Avanços · ${records(workspace.progressUpdates).length}`}><RecordList items={records(workspace.progressUpdates)} empty="Ainda não há avanços locais." render={(item) => <Item text={item.description} meta={formatDate(item.occurredOn)} />} /><TextForm label="Registrar avanço" placeholder="O que saiu do lugar?" submitLabel="Registrar avanço" onSubmit={(description) => commit(addProgressUpdate(workspace, project.id, { description }), 'Avanço registrado.')} /></Fold>
      <Fold title={`Pendências · ${records(workspace.pendingItems).filter((item) => !item.completedAt).length}`}><RecordList items={records(workspace.pendingItems).filter((item) => !item.completedAt)} empty="Nenhuma pendência aberta." render={(item) => <Item text={item.description} action="Concluir" onAction={() => commit(completePendingItem(workspace, item.id), 'Pendência concluída.')} editAction="Editar" onEdit={() => editText(item.description, (description) => commit(updatePendingItem(workspace, item.id, { description }), 'Pendência atualizada.'))} />} /><TextForm label="Nova pendência" placeholder="O que ainda falta?" submitLabel="Adicionar" onSubmit={(description) => commit(addPendingItem(workspace, project.id, { description }), 'Pendência adicionada.')} /></Fold>
      <Fold title={`Bloqueios · ${blockers.length}`} alert={blockers.length > 0}><RecordList items={blockers} empty="Nenhum bloqueio aberto." render={(item) => <Item text={item.description} action="Resolver" onAction={() => commit(resolveBlocker(workspace, item.id), 'Bloqueio resolvido.')} editAction="Editar" onEdit={() => editText(item.description, (description) => commit(updateBlocker(workspace, item.id, { description }), 'Bloqueio atualizado.'))} />} /><TextForm label="Registrar bloqueio" placeholder="O que está impedindo o avanço?" submitLabel="Registrar" onSubmit={(description) => commit(addBlocker(workspace, project.id, { description }), 'Bloqueio registrado.')} /></Fold>
      <Fold title={`Decisões · ${records(workspace.decisions).length}`}><RecordList items={records(workspace.decisions)} empty="Nenhuma decisão local registrada." render={(item) => <Item text={item.description} meta={item.rationale ?? undefined} />} /><DecisionForm onSubmit={(description, rationale) => commit(addDecision(workspace, project.id, { description, rationale }), 'Decisão registrada.')} /></Fold>
      <Fold title={`Marcos · ${records(workspace.milestones).filter((item) => !item.completedAt).length}`}><RecordList items={records(workspace.milestones).filter((item) => !item.completedAt)} empty="Nenhum marco aberto." render={(item) => <Item text={item.description} meta={item.dueOn ? `Data: ${formatDate(item.dueOn)}` : undefined} action="Concluir" onAction={() => commit(completeMilestone(workspace, item.id), 'Marco concluído.')} />} /><MilestoneForm onSubmit={(description, dueOn) => commit(addMilestone(workspace, project.id, { description, dueOn }), 'Marco registrado.')} /></Fold>
      <Fold title={`Histórico · ${history.length}`}><RecordList items={history} empty="Nenhum evento local neste projeto." render={(item) => <Item text={item.description} meta={formatDate(item.occurredOn)} />} /></Fold>
    </div><aside className="detail-side"><dl className="detail-meta"><div><dt>Origem</dt><dd>{context ? 'Contexto canônico com overlay local' : 'Somente local'}</dd></div><div><dt>Estado</dt><dd>{project.status === 'active' ? 'Em curso' : project.status === 'archived' ? 'Arquivado' : project.status}</dd></div>{context && <><div><dt>Estágio</dt><dd>{context.stage ?? 'Não classificado'}</dd></div><div><dt>Fonte</dt><dd>{context.source.url ? <a href={context.source.url} target="_blank" rel="noreferrer">{context.source.path}</a> : context.source.path}</dd></div></>}{context?.repositories.length ? <div><dt>Repositórios</dt><dd>{context.repositories.map((repository) => <a key={repository.name} href={`https://github.com/${repository.name}`} target="_blank" rel="noreferrer">{repository.name}<br /></a>)}</dd></div> : null}</dl></aside></div>
  </section>
}

function Fold({ title, alert, children }: { title: string; alert?: boolean; children: React.ReactNode }) { return <details className="fold" open={alert}><summary>{title}</summary><div className="fold-content">{children}</div></details> }
function RecordList<T>({ items, empty, render }: { items: T[]; empty: string; render(item: T): React.ReactNode }) { return items.length ? <ul className="record-list">{items.map((item, index) => <li key={index}>{render(item)}</li>)}</ul> : <p className="quiet-empty">{empty}</p> }
function Item({ text, meta, action, onAction, editAction, onEdit }: { text: string; meta?: string; action?: string; onAction?: () => void; editAction?: string; onEdit?: () => void }) { return <div className="record-item"><span><strong>{text}</strong>{meta && <small>{meta}</small>}</span><div>{editAction && <button className="button-quiet" onClick={onEdit}>{editAction}</button>}{action && <button className="button-quiet" onClick={onAction}>{action}</button>}</div></div> }
function TextForm({ label, placeholder, submitLabel, onSubmit }: { label: string; placeholder: string; submitLabel: string; onSubmit(description: string): void }) { const [description, setDescription] = useState(''); const [error, setError] = useState(''); const submit = (event: FormEvent) => { event.preventDefault(); try { onSubmit(description); setDescription(''); setError('') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível salvar.') } }; return <form className="inline-form" onSubmit={submit}><label>{label}<input value={description} placeholder={placeholder} onChange={(event) => setDescription(event.target.value)} /></label>{error && <p role="alert" className="form-error">{error}</p>}<button type="submit">{submitLabel}</button></form> }
function MilestoneForm({ onSubmit }: { onSubmit(description: string, dueOn: string | null): void }) { const [description, setDescription] = useState(''); const [dueOn, setDueOn] = useState(''); return <form className="inline-form" onSubmit={(event) => { event.preventDefault(); onSubmit(description, dueOn || null); setDescription(''); setDueOn('') }}><label>Novo marco<input value={description} onChange={(event) => setDescription(event.target.value)} /></label><label>Data opcional<input type="date" value={dueOn} onChange={(event) => setDueOn(event.target.value)} /></label><button type="submit">Adicionar</button></form> }
function DecisionForm({ onSubmit }: { onSubmit(description: string, rationale: string): void }) { const [description, setDescription] = useState(''); const [rationale, setRationale] = useState(''); return <form className="inline-form" onSubmit={(event) => { event.preventDefault(); onSubmit(description, rationale); setDescription(''); setRationale('') }}><label>Nova decisão<input value={description} onChange={(event) => setDescription(event.target.value)} /></label><label>Por quê?<input value={rationale} onChange={(event) => setRationale(event.target.value)} /></label><button type="submit">Registrar</button></form> }
function formatDate(value: string) { return new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium' }).format(new Date(value)) }
function editText(current: string, onConfirm: (value: string) => void) { const next = window.prompt('Atualizar texto', current); if (next !== null) onConfirm(next) }
